package material;

import static gregtech.api.unification.material.Materials.*;

import static tkcy.tktech.api.unification.materials.TkTechMaterials.*;
import static tkcy.tktech.api.unification.properties.PhysicalProperties.addPhysicalMaterialProperty;
import static tkcy.tktech.api.unification.properties.PhysicalPropertiesBuilder.initBuilder;

public class PhysicalMatProperty {

    public static void register() {

        addPhysicalMaterialProperty(Ammonia, initBuilder().mp(195).bp(240).hygroscopic());
        addPhysicalMaterialProperty(NitricOxide, initBuilder().mp(109).bp(121));
        addPhysicalMaterialProperty(SodiumPotassium, initBuilder().mp(261).pyrophoric().thermalConductivity(22));
        addPhysicalMaterialProperty(TitaniumTrifluoride, initBuilder().hygroscopic().mp(1470).bp(1670));
        addPhysicalMaterialProperty(AntimonyTrifluoride, initBuilder().mp(565).bp(649).hygroscopic());
        addPhysicalMaterialProperty(Aluminium, initBuilder().oxidizes().thermalConductivity(237));
        addPhysicalMaterialProperty(Argon, initBuilder().mp(84).bp(81));
        addPhysicalMaterialProperty(Arsenic, initBuilder().oxidizes());
        addPhysicalMaterialProperty(Barium, initBuilder().oxidizes());
        addPhysicalMaterialProperty(Beryllium, initBuilder().thermalConductivity(216).oxidizes().mp(1560).bp(2742));
        addPhysicalMaterialProperty(Bismuth, initBuilder().thermalConductivity(8).mp(545).bp(1837));
        addPhysicalMaterialProperty(Boron, initBuilder().thermalConductivity(27).mp(2349).bp(4200).oxidizes());
        addPhysicalMaterialProperty(Caesium, initBuilder().thermalConductivity(36).mp(302).bp(944).pyrophoric());
        addPhysicalMaterialProperty(Calcium, initBuilder().thermalConductivity(201).mp(1115).bp(1757).pyrophoric());
        addPhysicalMaterialProperty(Cadmium, initBuilder().thermalConductivity(97).mp(594).bp(1040).pyrophoric());
        addPhysicalMaterialProperty(Cerium, initBuilder().thermalConductivity(11).mp(1068).bp(3716).oxidizes());
        addPhysicalMaterialProperty(Chrome, initBuilder().thermalConductivity(94).mp(2180).bp(2944).oxidizes());
        addPhysicalMaterialProperty(Cobalt, initBuilder().thermalConductivity(100).mp(1768).bp(3200));
        addPhysicalMaterialProperty(Copper, initBuilder().thermalConductivity(401).mp(1358).bp(2835).oxidizes());
        addPhysicalMaterialProperty(Dysprosium, initBuilder().thermalConductivity(11).mp(1680).bp(2840).pyrophoric());
        addPhysicalMaterialProperty(Erbium, initBuilder().thermalConductivity(14).mp(1802).bp(3141));
        addPhysicalMaterialProperty(Europium, initBuilder().thermalConductivity(14).mp(1099).bp(1802).oxidizes());
        addPhysicalMaterialProperty(Fluorine, initBuilder().mp(53).bp(85));
        addPhysicalMaterialProperty(Gadolinium, initBuilder().thermalConductivity(11).mp(1545).bp(3546).oxidizes());
        addPhysicalMaterialProperty(Gallium, initBuilder().thermalConductivity(41).mp(303).bp(2676).oxidizes());
        addPhysicalMaterialProperty(Germanium, initBuilder().thermalConductivity(60).mp(1211).bp(3106));
        addPhysicalMaterialProperty(Gold, initBuilder().thermalConductivity(318).mp(1337).bp(3243));
        addPhysicalMaterialProperty(Hafnium, initBuilder().thermalConductivity(23).mp(2506).bp(4876).oxidizes());
        addPhysicalMaterialProperty(Indium, initBuilder().thermalConductivity(82).mp(430).bp(2345).oxidizes());
        addPhysicalMaterialProperty(Iridium, initBuilder().thermalConductivity(147).mp(2719).bp(4403));
        addPhysicalMaterialProperty(Iron, initBuilder().thermalConductivity(80).mp(1811).bp(3134).oxidizes());
        addPhysicalMaterialProperty(Krypton, initBuilder().mp(116).bp(120));
        addPhysicalMaterialProperty(Lanthanum, initBuilder().thermalConductivity(13).mp(1193).bp(3737).oxidizes());
        addPhysicalMaterialProperty(Lead, initBuilder().thermalConductivity(35).mp(600).bp(2022).oxidizes());
        addPhysicalMaterialProperty(Lithium, initBuilder().thermalConductivity(85).mp(454).bp(1603).oxidizes());
        addPhysicalMaterialProperty(Lutetium, initBuilder().thermalConductivity(16).mp(1925).bp(3675).oxidizes());
        addPhysicalMaterialProperty(Magnesium, initBuilder().thermalConductivity(156).mp(923).bp(1363).hygroscopic());
        addPhysicalMaterialProperty(Manganese, initBuilder().thermalConductivity(8).mp(1519).bp(2334).oxidizes());
        addPhysicalMaterialProperty(Molybdenum, initBuilder().thermalConductivity(138).mp(2896).bp(4912));
        addPhysicalMaterialProperty(Neodymium, initBuilder().thermalConductivity(17).mp(1295).bp(3347).oxidizes());
        addPhysicalMaterialProperty(Neon, initBuilder().thermalConductivity(18).mp(25).bp(27));
        addPhysicalMaterialProperty(Nickel, initBuilder().thermalConductivity(91).mp(1728).bp(3003).oxidizes());
        addPhysicalMaterialProperty(Niobium, initBuilder().thermalConductivity(54).mp(2750).bp(5017).oxidizes());
        addPhysicalMaterialProperty(Osmium, initBuilder().thermalConductivity(88).mp(3306).bp(5281).oxidizes());
        addPhysicalMaterialProperty(Palladium, initBuilder().thermalConductivity(72).mp(1828).bp(3236));
        addPhysicalMaterialProperty(Phosphorus, initBuilder().pyrophoric());
        addPhysicalMaterialProperty(Platinum, initBuilder().thermalConductivity(72).mp(2041).bp(4098));
        addPhysicalMaterialProperty(Potassium, initBuilder().thermalConductivity(103).mp(337).bp(1031).pyrophoric());
        addPhysicalMaterialProperty(Praseodymium, initBuilder().thermalConductivity(13).mp(1204).bp(3403).oxidizes());
        addPhysicalMaterialProperty(Promethium, initBuilder().thermalConductivity(18).mp(1315).bp(3273));
        addPhysicalMaterialProperty(Protactinium, initBuilder().thermalConductivity(47).oxidizes().mp(1841).bp(4300));
        addPhysicalMaterialProperty(Rhenium, initBuilder().thermalConductivity(48).mp(3459).bp(5903));
        addPhysicalMaterialProperty(Rhodium, initBuilder().thermalConductivity(150).mp(2237).bp(3698));
        addPhysicalMaterialProperty(Rubidium, initBuilder().thermalConductivity(58).pyrophoric().mp(312).bp(691));
        addPhysicalMaterialProperty(Ruthenium, initBuilder().thermalConductivity(117));
        addPhysicalMaterialProperty(Samarium, initBuilder().thermalConductivity(13).oxidizes());
        addPhysicalMaterialProperty(Scandium, initBuilder().thermalConductivity(16).oxidizes().mp(1814).bp(3109));
        addPhysicalMaterialProperty(Selenium, initBuilder().mp(494).bp(958));
        addPhysicalMaterialProperty(Silicon, initBuilder().thermalConductivity(149));
        addPhysicalMaterialProperty(Silver, initBuilder().thermalConductivity(429));
        addPhysicalMaterialProperty(Sodium, initBuilder().thermalConductivity(142).pyrophoric());
        addPhysicalMaterialProperty(Strontium, initBuilder().thermalConductivity(35).oxidizes().mp(1050).bp(1650));
        addPhysicalMaterialProperty(Tantalum, initBuilder().thermalConductivity(57).mp(3290).bp(5731));
        addPhysicalMaterialProperty(Tellurium, initBuilder().thermalConductivity(3).mp(723).bp(1261));
        addPhysicalMaterialProperty(Terbium, initBuilder().thermalConductivity(11).mp(1629).bp(3396));
        addPhysicalMaterialProperty(Thorium, initBuilder().thermalConductivity(54).oxidizes().hygroscopic());
        addPhysicalMaterialProperty(Thallium, initBuilder().thermalConductivity(46).oxidizes());
        addPhysicalMaterialProperty(Thulium, initBuilder().thermalConductivity(17).oxidizes());
        addPhysicalMaterialProperty(Tin, initBuilder().thermalConductivity(67).mp(505).bp(2875));
        addPhysicalMaterialProperty(Titanium, initBuilder().thermalConductivity(22).oxidizes());
        addPhysicalMaterialProperty(Tungsten, initBuilder().thermalConductivity(173));
        addPhysicalMaterialProperty(Uranium, initBuilder().thermalConductivity(27).oxidizes());
        addPhysicalMaterialProperty(Uranium235, initBuilder().thermalConductivity(27).oxidizes());
        addPhysicalMaterialProperty(Vanadium, initBuilder().thermalConductivity(31).oxidizes());
        addPhysicalMaterialProperty(Ytterbium, initBuilder().thermalConductivity(38).oxidizes());
        addPhysicalMaterialProperty(Yttrium, initBuilder().thermalConductivity(17).oxidizes());
        addPhysicalMaterialProperty(Zinc, initBuilder().thermalConductivity(116).pyrophoric());
        addPhysicalMaterialProperty(Zirconium, initBuilder().thermalConductivity(22));
        addPhysicalMaterialProperty(Nitrobenzene, initBuilder().bp(484).mp(279));
        addPhysicalMaterialProperty(Methane, initBuilder().mp(91).bp(112).flameTemperature(2173).autoIgnitionTemperature(810));
        addPhysicalMaterialProperty(Epichlorohydrin, initBuilder().mp(247).bp(391));
        addPhysicalMaterialProperty(Monochloramine, initBuilder().mp(207));
        addPhysicalMaterialProperty(Chloroform, initBuilder().mp(210).bp(334));
        addPhysicalMaterialProperty(Cumene, initBuilder().mp(177).bp(425).autoIgnitionTemperature(697));
        addPhysicalMaterialProperty(Tetrafluoroethylene, initBuilder().bp(197).mp(131));
        addPhysicalMaterialProperty(Chloromethane, initBuilder().autoIgnitionTemperature(898).mp(176).bp(249));
        addPhysicalMaterialProperty(AllylChloride, initBuilder().mp(138).bp(318).autoIgnitionTemperature(663));
        addPhysicalMaterialProperty(Isoprene, initBuilder().bp(307).mp(129));
        addPhysicalMaterialProperty(Propane, initBuilder().mp(86).bp(231).autoIgnitionTemperature(743).flameTemperature(2243));
        addPhysicalMaterialProperty(Propene, initBuilder().bp(223).mp(88).flameTemperature(2223).autoIgnitionTemperature(728));
        addPhysicalMaterialProperty(Ethane, initBuilder().mp(90).bp(185).autoIgnitionTemperature(745).flameTemperature(2235));
        addPhysicalMaterialProperty(Butene, initBuilder().flameTemperature(2200).autoIgnitionTemperature(658).bp(267).mp(88));
        addPhysicalMaterialProperty(Butane, initBuilder().mp(136).bp(273).autoIgnitionTemperature(678).flameTemperature(2200));
        addPhysicalMaterialProperty(VinylAcetate, initBuilder().bp(346).mp(180).autoIgnitionTemperature(700).flameTemperature(2200));
        addPhysicalMaterialProperty(MethylAcetate, initBuilder().bp(330).mp(175));
        addPhysicalMaterialProperty(Ethenone, initBuilder().mp(123).bp(217));
        addPhysicalMaterialProperty(Tetranitromethane, initBuilder().bp(399).mp(287).flameTemperature(3780).autoIgnitionTemperature(533));
        addPhysicalMaterialProperty(Dimethylamine, initBuilder().autoIgnitionTemperature(674).mp(180).bp(282).flameTemperature(2500));
        addPhysicalMaterialProperty(Dimethylhydrazine, initBuilder().bp(337).mp(216).autoIgnitionTemperature(521).flameTemperature(2700));
        addPhysicalMaterialProperty(DinitrogenTetroxide, initBuilder().mp(262).bp(295));
        addPhysicalMaterialProperty(Dimethyldichlorosilane, initBuilder().mp(197).bp(343).autoIgnitionTemperature(690).flameTemperature(2280));
        addPhysicalMaterialProperty(Styrene, initBuilder().bp(418).mp(243));
        addPhysicalMaterialProperty(Butadiene, initBuilder().mp(164).bp(269).autoIgnitionTemperature(687).flameTemperature(2223));
        addPhysicalMaterialProperty(AceticAcid, initBuilder().mp(290).bp(391).autoIgnitionTemperature(700).flameTemperature(2123));
        addPhysicalMaterialProperty(Phenol, initBuilder().bp(455).mp(314).hygroscopic());
        addPhysicalMaterialProperty(BisphenolA, initBuilder().mp(428).bp(525, 1722));
        addPhysicalMaterialProperty(VinylChloride, initBuilder().bp(260).mp(119).autoIgnitionTemperature(745).flameTemperature(2180));
        addPhysicalMaterialProperty(Ethylene, initBuilder().mp(104).bp(170).autoIgnitionTemperature(816).flameTemperature(2250));
        addPhysicalMaterialProperty(Benzene, initBuilder().autoIgnitionTemperature(771).bp(353).mp(279).flameTemperature(2250));
        addPhysicalMaterialProperty(Acetone, initBuilder().autoIgnitionTemperature(738).bp(329).mp(178).flameTemperature(2250));
        addPhysicalMaterialProperty(Glycerol, initBuilder().bp(563).mp(291));
        addPhysicalMaterialProperty(Methanol, initBuilder().autoIgnitionTemperature(658).bp(338).mp(176).flameTemperature(2150));
        addPhysicalMaterialProperty(Ethanol, initBuilder().bp(351).mp(159).autoIgnitionTemperature(642).flameTemperature(2250));
        addPhysicalMaterialProperty(Toluene, initBuilder().autoIgnitionTemperature(753).bp(384).mp(178).flameTemperature(2300));
        addPhysicalMaterialProperty(PhthalicAcid, initBuilder().mp(480));
        addPhysicalMaterialProperty(Chlorobenzene, initBuilder().mp(228).bp(405).autoIgnitionTemperature(813).flameTemperature(2220));
        addPhysicalMaterialProperty(Octane, initBuilder().flameTemperature(2420).autoIgnitionTemperature(493).bp(398).mp(216));
        addPhysicalMaterialProperty(EthylTertButylEther, initBuilder().mp(179).bp(344).autoIgnitionTemperature(648).flameTemperature(2220));
        addPhysicalMaterialProperty(Ethylbenzene, initBuilder().autoIgnitionTemperature(703).bp(409).mp(178).flameTemperature(2220));
        addPhysicalMaterialProperty(Naphthalene, initBuilder().autoIgnitionTemperature(798).mp(351).bp(491).flameTemperature(2220));
        addPhysicalMaterialProperty(Cyclohexane, initBuilder().autoIgnitionTemperature(518).bp(354).mp(280).flameTemperature(2220));
        addPhysicalMaterialProperty(NitrosylChloride, initBuilder().bp(268).mp(214));
        addPhysicalMaterialProperty(Butyraldehyde, initBuilder().autoIgnitionTemperature(503).bp(348).mp(176).flameTemperature(2120));

    }
}
